name: Unzip File Automatically

on:
  push:
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Unzip uploaded archive
        run: |
          unzip -o *.zip -d .
          rm *.zip

      - name: Commit Extracted Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto unzipped contents to root"
          
